model:
  backbone: resnet18
  ckpt_pretrained:
  num_classes: 10

dataset: data/cifar10

dataloaders:
  train_batch_size: 200 # the higher - the better
  valid_batch_size: 200
  num_workers: 16 # set this to num of threads in your CPU

optimizer:
  name: SGD
  params:
    lr: 0.001

criterion:
  name: 'CrossEntropy'

